/*
* generated by Xtext
*/
package reprotool.fm.nusmv.lang.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class NuSmvLangOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
