/*
* generated by Xtext
*/
package reprotool.txtspec.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import reprotool.txtspec.services.TxtSpecGrammarAccess;

public class TxtSpecParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TxtSpecGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS");
	}
	
	@Override
	protected reprotool.txtspec.parser.antlr.internal.InternalTxtSpecParser createParser(XtextTokenStream stream) {
		return new reprotool.txtspec.parser.antlr.internal.InternalTxtSpecParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Document";
	}
	
	public TxtSpecGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TxtSpecGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
