/*
* generated by Xtext
*/
package reprotool.txtspec.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TxtSpecAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("reprotool/txtspec/parser/antlr/internal/InternalTxtSpec.tokens");
	}
}
