/*
* generated by Xtext
*/
package reprotool.txtspec.ui.contentassist;

import reprotool.txtspec.ui.contentassist.AbstractTxtSpecProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class TxtSpecProposalProvider extends AbstractTxtSpecProposalProvider {

}
