/*
* generated by Xtext
*/
package reprotool.txtspec.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class TxtSpecOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
