/*
 * generated by Xtext
 */
package reprotool.ide.txtuc;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TxtUseCaseRuntimeModule extends reprotool.ide.txtuc.AbstractTxtUseCaseRuntimeModule {

}
