/*
 * generated by Xtext
 */
package reprotool.fm.nusmv.lang;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class NuSmvInputLanguageRuntimeModule extends reprotool.fm.nusmv.lang.AbstractNuSmvInputLanguageRuntimeModule {

}
