<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ast"
    nsURI="http://d3s.mff.cuni.cz/reprotool/model/structure/ast" nsPrefix="ast">
  <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="#//CodeElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//MethodVisibility"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//CodeElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//Method"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MethodVisibility">
    <eLiterals name="private"/>
    <eLiterals name="public" value="1"/>
  </eClassifiers>
</ecore:EPackage>
