<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="comp"
    nsURI="http://d3s.mff.cuni.cz/reprotool/model/comp" nsPrefix="comp">
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedInterfaces" upperBound="-1"
        eType="#//CompInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredInterfaces" upperBound="-1"
        eType="#//CompInterface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompInterface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceType" eType="#//CompInterfaceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompInterfaceType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
