/*
* generated by Xtext
*/
package reprotool.ide.txtuc.ui.contentassist;

import reprotool.ide.txtuc.ui.contentassist.AbstractTxtUseCaseProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class TxtUseCaseProposalProvider extends AbstractTxtUseCaseProposalProvider {

}
