/*
 * generated by Xtext
 */
package reprotool.fm.nusmv.lang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class NuSmvLangUiModule extends reprotool.fm.nusmv.lang.ui.AbstractNuSmvLangUiModule {
	public NuSmvLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
