/*
 * generated by Xtext
 */
package reprotool.txtspec.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TxtSpecExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return reprotool.txtspec.ui.internal.TxtSpecActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return reprotool.txtspec.ui.internal.TxtSpecActivator.getInstance().getInjector("reprotool.txtspec.TxtSpec");
	}
	
}
