/*
 * generated by Xtext
 */
package reprotool.fm.nusmv.lang.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class NuSmvLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return reprotool.fm.nusmv.lang.ui.internal.NuSmvLangActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return reprotool.fm.nusmv.lang.ui.internal.NuSmvLangActivator.getInstance().getInjector("reprotool.fm.nusmv.lang.NuSmvLang");
	}
	
}
