/*
 * generated by Xtext
 */
package reprotool.txtspec.formatting;

import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;

import reprotool.txtspec.services.TxtSpecGrammarAccess;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#formatting
 * on how and when to use it 
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
public class TxtSpecFormatter extends AbstractDeclarativeFormatter {
	
	@Override
	protected void configureFormatting(FormattingConfig c) {

		TxtSpecGrammarAccess g = (TxtSpecGrammarAccess) getGrammarAccess();
		c.setLinewrap().after( g.getUrlParamRule() );
	}
}
