<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="nuSmvLang"
    nsURI="http://d3s.mff.cuni.cz/reprotool/nusmv/lang" nsPrefix="nuSmvLang">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1"
        eType="#//Module" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="moduleElement" upperBound="-1"
        eType="#//ModuleElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MainModule" eSuperTypes="#//Module"/>
  <eClassifiers xsi:type="ecore:EClass" name="OtherModule" eSuperTypes="#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//FormalParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration" eSuperTypes="#//ModuleElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vars" upperBound="-1" eType="#//VarBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IVariableDeclaration" eSuperTypes="#//ModuleElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vars" upperBound="-1" eType="#//VarBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FrozenVariableDeclaration" eSuperTypes="#//ModuleElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vars" upperBound="-1" eType="#//VarBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VarBody">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="varId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeSpecifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefineDeclaration" eSuperTypes="#//ModuleElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="defineBodies" upperBound="-1"
        eType="#//DefineBody" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefineBody">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="varId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assignment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantsDeclaration" eSuperTypes="#//ModuleElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constants" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssignConstraint" eSuperTypes="#//ModuleElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodies" upperBound="-1"
        eType="#//AssignBody" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssignBody">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="varId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VarBodyAssign" eSuperTypes="#//AssignBody">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assignment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitBody" eSuperTypes="#//AssignBody">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initExpr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NextBody" eSuperTypes="#//AssignBody">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nextExpr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransConstraint" eSuperTypes="#//ModuleElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transExpr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitConstraint" eSuperTypes="#//ModuleElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initExpr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvarConstraint" eSuperTypes="#//ModuleElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invarExpr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FairnessConstraint" eSuperTypes="#//ModuleElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="FairnessExpression" eSuperTypes="#//FairnessConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fairnessExpr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JusticeExpression" eSuperTypes="#//FairnessConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="justiceExpr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompassionExpression" eSuperTypes="#//FairnessConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstCompassionExpr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secondCompassionExpr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvarSpecification" eSuperTypes="#//ModuleElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invarExpr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CtlSpecification" eSuperTypes="#//ModuleElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameKeyWord" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ctlExpr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LtlSpecification" eSuperTypes="#//ModuleElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ltlExpr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeSpecifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleType" eSuperTypes="#//TypeSpecifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleType" eSuperTypes="#//TypeSpecifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="#//Module"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="params" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FormalParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paramId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanType" eSuperTypes="#//SimpleType"/>
  <eClassifiers xsi:type="ecore:EClass" name="WordType" eSuperTypes="#//SimpleType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wordNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnsignedWordType" eSuperTypes="#//SimpleType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uWordNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SignedWordType" eSuperTypes="#//SimpleType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signedNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumType" eSuperTypes="#//SimpleType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RangeType" eSuperTypes="#//SimpleType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="low" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="high" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayType" eSuperTypes="#//SimpleType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bounds" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//SimpleType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AsyncrProcessType" eSuperTypes="#//ModuleType"/>
  <eClassifiers xsi:type="ecore:EClass" name="SyncrProcessType" eSuperTypes="#//ModuleType"/>
</ecore:EPackage>
