/*
 * generated by Xtext
 */
package reprotool.ide.txtuc.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TxtUseCaseUiModule extends reprotool.ide.txtuc.ui.AbstractTxtUseCaseUiModule {
	public TxtUseCaseUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
