/*
* generated by Xtext
*/
package reprotool.fm.nusmv.lang.ui.contentassist;

import reprotool.fm.nusmv.lang.ui.contentassist.AbstractNuSmvInputLanguageProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class NuSmvInputLanguageProposalProvider extends AbstractNuSmvInputLanguageProposalProvider {

}
