/*
* generated by Xtext
*/
package reprotool.fm.nusmv.lang.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import reprotool.fm.nusmv.lang.services.NuSmvLangGrammarAccess;

public class NuSmvLangParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private NuSmvLangGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected reprotool.fm.nusmv.lang.parser.antlr.internal.InternalNuSmvLangParser createParser(XtextTokenStream stream) {
		return new reprotool.fm.nusmv.lang.parser.antlr.internal.InternalNuSmvLangParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public NuSmvLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(NuSmvLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
