/*
 * generated by Xtext
 */
package reprotool.txtspec;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TxtSpecRuntimeModule extends reprotool.txtspec.AbstractTxtSpecRuntimeModule {

}
