/*
* generated by Xtext
*/
package reprotool.txtspec.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import reprotool.txtspec.services.TxtSpecGrammarAccess;

public class TxtSpecParser extends AbstractContentAssistParser {
	
	@Inject
	private TxtSpecGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected reprotool.txtspec.ui.contentassist.antlr.internal.InternalTxtSpecParser createParser() {
		reprotool.txtspec.ui.contentassist.antlr.internal.InternalTxtSpecParser result = new reprotool.txtspec.ui.contentassist.antlr.internal.InternalTxtSpecParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getBlockAccess().getAlternatives(), "rule__Block__Alternatives");
					put(grammarAccess.getModelElementBlockAccess().getGroup(), "rule__ModelElementBlock__Group__0");
					put(grammarAccess.getModelElementBlockContentAccess().getGroup(), "rule__ModelElementBlockContent__Group__0");
					put(grammarAccess.getDocumentAccess().getBlocksAssignment(), "rule__Document__BlocksAssignment");
					put(grammarAccess.getModelElementBlockAccess().getUrlAssignment_1(), "rule__ModelElementBlock__UrlAssignment_1");
					put(grammarAccess.getModelElementBlockAccess().getContentAssignment_2(), "rule__ModelElementBlock__ContentAssignment_2");
					put(grammarAccess.getModelElementBlockContentAccess().getBlocksAssignment_1(), "rule__ModelElementBlockContent__BlocksAssignment_1");
					put(grammarAccess.getTextBlockAccess().getWordsAssignment(), "rule__TextBlock__WordsAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			reprotool.txtspec.ui.contentassist.antlr.internal.InternalTxtSpecParser typedParser = (reprotool.txtspec.ui.contentassist.antlr.internal.InternalTxtSpecParser) parser;
			typedParser.entryRuleDocument();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS" };
	}
	
	public TxtSpecGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TxtSpecGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
