/*
 * generated by Xtext
 */
package reprotool.fm.nusmv.lang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class NuSmvInputLanguageUiModule extends reprotool.fm.nusmv.lang.ui.AbstractNuSmvInputLanguageUiModule {
	public NuSmvInputLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
