/*
 * generated by Xtext
 */
package reprotool.txtspec.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TxtSpecUiModule extends
		reprotool.txtspec.ui.AbstractTxtSpecUiModule {
	public TxtSpecUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
