/*
* generated by Xtext
*/
package reprotool.fm.nusmv.lang.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class NuSmvLangAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("reprotool/fm/nusmv/lang/parser/antlr/internal/InternalNuSmvLang.tokens");
	}
}
