<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="reprotool"
    nsURI="http://d3s.mff.cuni.cz/reprotool" nsPrefix="reprotool">
  <eSubpackages name="model" nsURI="http://d3s.mff.cuni.cz/reprotool/model" nsPrefix="model">
    <eSubpackages name="linguistic" nsURI="http://d3s.mff.cuni.cz/reprotool/model/linguistic"
        nsPrefix="linguistic">
      <eClassifiers xsi:type="ecore:EClass" name="SentenceNode">
        <eStructuralFeatures xsi:type="ecore:EReference" name="childFragments" upperBound="-1"
            eType="#//model/linguistic/SentenceNode"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Word" eSuperTypes="#//model/linguistic/SentenceNode">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="wordStr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="wordType" eType="#//model/linguistic/EWordType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="EWordType">
        <eLiterals name="NotImportant"/>
        <eLiterals name="Subject" value="1"/>
        <eLiterals name="IndirectObject" value="2"/>
        <eLiterals name="Verb" value="3" literal="Verb"/>
        <eLiterals name="RepresentativeObject" value="4"/>
        <eLiterals name="GotoTarget" value="5"/>
        <eLiterals name="ConditionLabel" value="6"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
