<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://d3s.mff.cuni.cz/reprotool/model" nsPrefix="model">
  <eSubpackages name="lts" nsURI="http://d3s.mff.cuni.cz/reprotool/model/lts" nsPrefix="lts">
    <eClassifiers xsi:type="ecore:EClass" name="Transition" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sentence" eType="#//usecase/ParseableElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
          eType="#//lts/State"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="#//lts/State"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tokens" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="State"/>
    <eClassifiers xsi:type="ecore:EClass" name="StateMachine">
      <eStructuralFeatures xsi:type="ecore:EReference" name="initialState" lowerBound="1"
          eType="#//lts/State"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="abortState" eType="#//lts/State"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="successState" lowerBound="1"
          eType="#//lts/State"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allTransitions" upperBound="-1"
          eType="#//lts/Transition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allStates" upperBound="-1"
          eType="#//lts/State" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActionTransition" eSuperTypes="#//lts/Transition"/>
  </eSubpackages>
  <eSubpackages name="usecase" nsURI="http://d3s.mff.cuni.cz/reprotool/model/usecase"
      nsPrefix="usecase">
    <eClassifiers xsi:type="ecore:EClass" name="UseCase" eSuperTypes="#//swproj/ReqCover #//traceability/TraceableEntity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="primaryActor" lowerBound="1"
          eType="#//swproj/Actor"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mainScenario" lowerBound="1"
          eType="#//usecase/Scenario" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParseableElement" abstract="true"
        interface="true" eSuperTypes="#//swproj/ReqCover">
      <eOperations name="getLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="textNodes" upperBound="-1"
          eType="#//linguistic/actionpart/Text" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
          eType="#//usecase/annotate/StepAnnotation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Scenario">
      <eStructuralFeatures xsi:type="ecore:EReference" name="steps" upperBound="-1"
          eType="#//usecase/UseCaseStep" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="preconditions" upperBound="-1"
          eType="#//usecase/Condition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="postconditions" upperBound="-1"
          eType="#//usecase/Condition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Condition" eSuperTypes="#//usecase/ParseableElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="UseCaseStep" eSuperTypes="#//usecase/ParseableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="extensions" upperBound="-1"
          eType="#//usecase/Scenario" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variations" upperBound="-1"
          eType="#//usecase/Scenario" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
          eType="#//linguistic/action/Action" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="softwareProject" eType="#//swproj/SoftwareProject"
          changeable="false" volatile="true" transient="true" unsettable="true" derived="true"/>
    </eClassifiers>
    <eSubpackages name="annotate" nsURI="http://d3s.mff.cuni.cz/reprotool/model/usecase/annotate"
        nsPrefix="annotate">
      <eClassifiers xsi:type="ecore:EClass" name="StepAnnotation">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="annotationType" lowerBound="1"
            eType="#//usecase/annotate/StepAnnotationType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="StepAnnotationType" abstract="true"
          interface="true">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TemporalAnnotation" eSuperTypes="#//usecase/annotate/StepAnnotationType"/>
      <eClassifiers xsi:type="ecore:EClass" name="SpecialAnnotation" abstract="true"
          interface="true" eSuperTypes="#//usecase/annotate/StepAnnotationType"/>
      <eClassifiers xsi:type="ecore:EClass" name="AnnotationSet" abstract="true" interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="LTLAnnotationSet" eSuperTypes="#//usecase/annotate/AnnotationSet">
        <eStructuralFeatures xsi:type="ecore:EReference" name="contains" lowerBound="1"
            upperBound="-1" eType="#//usecase/annotate/TemporalAnnotation" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="ltlFormula" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SpecialAnnotationSet" eSuperTypes="#//usecase/annotate/AnnotationSet">
        <eStructuralFeatures xsi:type="ecore:EReference" name="contains" lowerBound="1"
            upperBound="-1" eType="#//usecase/annotate/SpecialAnnotation" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TraceAnnotation" eSuperTypes="#//usecase/annotate/StepAnnotationType #//usecase/annotate/AnnotationSet #//usecase/annotate/SpecialAnnotation"/>
      <eClassifiers xsi:type="ecore:EClass" name="OnAnnotation" eSuperTypes="#//usecase/annotate/StepAnnotationType #//usecase/annotate/AnnotationSet #//usecase/annotate/SpecialAnnotation"/>
      <eClassifiers xsi:type="ecore:EClass" name="CTLAnnotationSet" eSuperTypes="#//usecase/annotate/AnnotationSet">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="ctlFormula" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="contains" lowerBound="1"
            upperBound="-1" eType="#//usecase/annotate/TemporalAnnotation" containment="true"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="swproj" nsURI="http://d3s.mff.cuni.cz/reprotool/model/swproj"
      nsPrefix="swproj">
    <eClassifiers xsi:type="ecore:EClass" name="SoftwareProject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="actors" upperBound="-1"
          eType="#//swproj/Actor" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" upperBound="-1"
          eType="#//swproj/Requirement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="srsDocuments" upperBound="-1"
          eType="#//doc/Document"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="useCases" upperBound="-1"
          eType="#//usecase/UseCase" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotationSets" upperBound="-1"
          eType="#//usecase/annotate/AnnotationSet" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="A project "/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="conceptualObjects" upperBound="-1"
          eType="#//swproj/ConceptualObject" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//traceability/TraceableEntity #//swproj/DomainElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="childrenActors" upperBound="-1"
          eType="#//swproj/Actor" eOpposite="#//swproj/Actor/parentActor"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parentActor" eType="#//swproj/Actor"
          eOpposite="#//swproj/Actor/childrenActors"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Requirement" eSuperTypes="#//traceability/TraceableEntity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="originalText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="originalId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NFRequirement" eSuperTypes="#//swproj/Requirement"/>
    <eClassifiers xsi:type="ecore:EClass" name="ReqCover" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="relatedRequirements"
          upperBound="-1" eType="#//swproj/Requirement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DomainElement" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConceptualObject" eSuperTypes="#//swproj/DomainElement"/>
  </eSubpackages>
  <eSubpackages name="traceability" nsURI="http://d3s.mff.cuni.cz/reprotool/model/traceability"
      nsPrefix="traceability">
    <eClassifiers xsi:type="ecore:EClass" name="TraceableEntity" abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="TraceLink">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
          lowerBound="1" upperBound="-1" eType="#//traceability/TraceableEntity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
          lowerBound="1" upperBound="-1" eType="#//traceability/TraceableEntity"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="linguistic" nsURI="http://d3s.mff.cuni.cz/reprotool/model/linguistic"
      nsPrefix="linguistic">
    <eSubpackages name="actionpart" nsURI="http://d3s.mff.cuni.cz/reprotool/model/linguistic/actionpart"
        nsPrefix="actionpart">
      <eClassifiers xsi:type="ecore:EClass" name="Text">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="actionPart" eType="#//linguistic/actionpart/ActionPart"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="lemmaForm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="posTag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SentenceActor" eSuperTypes="#//linguistic/actionpart/ActionPart">
        <eStructuralFeatures xsi:type="ecore:EReference" name="actor" lowerBound="1"
            eType="#//swproj/Actor"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SentenceActionParam" eSuperTypes="#//linguistic/actionpart/ActionPart">
        <eStructuralFeatures xsi:type="ecore:EReference" name="conceptualObject" lowerBound="1"
            eType="#//swproj/ConceptualObject"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ActionPart" abstract="true" interface="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="#//linguistic/actionpart/Text"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="action" nsURI="http://d3s.mff.cuni.cz/reprotool/model/linguistic/action"
        nsPrefix="action">
      <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true" interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="FromSystem" eSuperTypes="#//linguistic/action/Communication">
        <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" lowerBound="1"
            eType="#//linguistic/actionpart/SentenceActor" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Internal" eSuperTypes="#//linguistic/action/Communication"/>
      <eClassifiers xsi:type="ecore:EClass" name="Goto" eSuperTypes="#//linguistic/action/Action #//linguistic/actionpart/ActionPart">
        <eStructuralFeatures xsi:type="ecore:EReference" name="gotoTarget" lowerBound="1"
            eType="#//usecase/UseCaseStep" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Unknown" eSuperTypes="#//linguistic/action/Action"/>
      <eClassifiers xsi:type="ecore:EClass" name="UseCaseInclude" eSuperTypes="#//linguistic/action/Action #//linguistic/actionpart/ActionPart">
        <eStructuralFeatures xsi:type="ecore:EReference" name="includeTarget" lowerBound="1"
            eType="#//usecase/UseCase" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AbortUseCase" eSuperTypes="#//linguistic/action/Action"/>
      <eClassifiers xsi:type="ecore:EClass" name="ToSystem" eSuperTypes="#//linguistic/action/Communication">
        <eStructuralFeatures xsi:type="ecore:EReference" name="sender" lowerBound="1"
            eType="#//linguistic/actionpart/SentenceActor" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Communication" abstract="true" interface="true"
          eSuperTypes="#//linguistic/action/Action">
        <eStructuralFeatures xsi:type="ecore:EReference" name="actionParam" upperBound="-1"
            eType="#//linguistic/actionpart/SentenceActionParam" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="actionName" lowerBound="1"
            eType="#//linguistic/actionpart/Text"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="ast" nsURI="http://d3s.mff.cuni.cz/reprotool/model/structure/ast"
      nsPrefix="ast">
    <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="#//ast/CodeElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//ast/MethodVisibility"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//ast/CodeElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
          eType="#//ast/Method"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CodeElement" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="MethodVisibility">
      <eLiterals name="private"/>
      <eLiterals name="public" value="1"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="comp" nsURI="http://d3s.mff.cuni.cz/reprotool/model/comp" nsPrefix="comp">
    <eClassifiers xsi:type="ecore:EClass" name="Component">
      <eStructuralFeatures xsi:type="ecore:EReference" name="providedInterfaces" upperBound="-1"
          eType="#//comp/CompInterface"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredInterfaces" upperBound="-1"
          eType="#//comp/CompInterface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompInterface">
      <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceType" eType="#//comp/CompInterfaceType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompInterfaceType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="signature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="doc" nsURI="http://d3s.mff.cuni.cz/reprotool/model/structure/doc"
      nsPrefix="doc">
    <eClassifiers xsi:type="ecore:EClass" name="Document">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sections" upperBound="-1"
          eType="#//doc/Section" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Section">
      <eStructuralFeatures xsi:type="ecore:EReference" name="paragraphs" upperBound="-1"
          eType="#//doc/Paragraph" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Paragraph" eSuperTypes="#//traceability/TraceableEntity"/>
  </eSubpackages>
</ecore:EPackage>
